commerce_payment.commerce_payment_gateway.plugin.ik_commerce:
  type: commerce_payment_gateway_configuration
  mapping:
      sid:
        type: string
        label: 'Vendor account number'
      secret_word:
        type: string
        label: 'Secret key'
      test_word:
        type: string
        label: 'Test key'
      api_mode:
        type: boolean
        label: 'Enable API/Disable API'
      api_id:
        type: string
        label: 'API Id'
      api_key:
        type: string
        label: 'API Key'
      server:
        type: string
        label: 'server'
      hostAccount:
        type: string
        label: 'hostAccount'
      hostPaySystem:
        type: string
        label: 'hostPaySystem'