# Schema for the configuration files of the uc_interkassa module.
# Модуль разработан в компании GateOn предназначен для CMS Drupal 8.2.x + Ubercart 4
# Сайт разработчикa: www.gateon.net
# E-mail: www@smartbyte.pro
# Версия: 1.2

uc_interkassa.settings:
  type: config_object
  label: 'Interkassa payment method configuration settings'
  mapping:
    test_mode:
      type: boolean
      label: 'Test mode'
    sid:
      type: string
      label: 'Vendor account number'
    secret_word:
      type: string
      label: 'Secret key'
    test_word:
      type: string
      label: 'Test key'
    api_mode:
      type: boolean
      label: 'Enable API/Disable API'
    api_id:
      type: string
      label: 'API Id'
    api_key:
      type: string
      label: 'API Key'
    server:
      type: string
      label: 'server'
    hostAccount:
      type: string
      label: 'hostAccount'


